---
title: "Blogposts"
output:
  html_document:
    css: "style.css"
    includes:
      after_body: footer.html
      in_header: header.html
---

<head>
<title>Nicolai Berk - Political Science and Data Analysis | Projects</title>
<meta name="description" content="Here I describe some of my projects in more depths to a broader audience, with the aim of broadening the understanding of a particular problem.">
</head>


# {.tabset .tabset-fade}

```{r setup, echo=F}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F)
```


***

## Measuring Accommodation to the Radical Right

This post is part of a [larger project](https://github.com/nicolaiberk/SMLSE).

```{r plot, echo = F}
library(ggplot2)
dta <- data(cars)

p1 <- 
  ggplot(cars, 
           aes(x = dist, 
               y = speed))+
  geom_point()

p1

```

## Radical Right Success and Immigration Attention

```{r plotly, echo = F}
library(plotly)
p2 <- plot_ly(cars, x = ~dist, y = ~speed)
p2

```


```{r shiny, echo = F}
knitr::include_app(" https://nicolai-student.shinyapps.io/test/", height = "600pt") 
```
