---
title: "Academic Work"
output:
  html_document:
    css: "style.css"
    includes:
      in_header: header.html
      after_body: footer.html
---
<!-- # {.tabset .tabset-fade} -->

<head>
<title>Nicolai Berk | Academic Work</title>
<meta name="description" content="These are some of the projects, papers, presentations, datasets, and other stuff I have been working on in the past.">
</head>


<div class = "col-md-8" margin = "auto">

<br>

### Work in progress

<br>


#### The Causal Effect of Media Frames on Issue Definitions
**Dissertation project exploiting a natural shift in the media framing of migration to estimate the effect of framing on voters' issue definitions**


[Working Paper](https://github.com/nicolaiberk/bild/raw/main/paper/Manuscript_Framing.pdf) | 
[Github](https://github.com/nicolaiberk/bild) | 
[Slides](https://github.com/nicolaiberk/bild/raw/main/pres/Presentation.pdf)
  

March 2021 -- today


<br>


#### Frame Competition
**Dissertation project assessing the impact of issue framing in the media on party competition**

[Working Paper](https://github.com/nicolaiberk/FrameCompetition/raw/main/paper/Manuscript.pdf) | 
[Github](https://github.com/nicolaiberk/FrameCompetition)

July 2022 -- today


<br>


#### Leading by Example? How Elite Behaviour affects Individual Vaccination Decisions
**Ongoing project assessing the impact of party cues on vaccination behaviour**

[Github](https://github.com/nicolaiberk/PartyVac) | 
[Slides](https://github.com/nicolaiberk/PartyVac/raw/main/pres/Presentation.pdf)

May 2022 -- today



<br>

#### Right-Wing Terrorist Attacks, the Media’s Reactions, and Radical Right Party Support
**Ongoing project (with Werner Krause) studying media reactions to radical-right terrorism in Germany**

February 2021 -- today


<br>



#### Measuring Rhetorical Similarity with Supervised Machine Learning 
**Working paper on the measurement of rhetorical similarity in political speech**

[Working Paper](https://github.com/nicolaiberk/SMLSE/raw/master/main.pdf) | 
[Github](https://github.com/nicolaiberk/SMLSE) | 
[Slides](https://www.dropbox.com/s/5zo85ak86hkujl0/Draft141020%20%281%29.pdf?dl=0)
  

March 2020 -- today

<br>

***

<br>

### Publications

<br>

#### "Die Nationalratswahl 2017 unter besonderer Berücksichtigung der Silberstein-Affäre"
**Book chapter in: "Blauer Band" (Eds. B. Weßels \& H. Schoen), co-authored with Julia Partheymüller and Jakob-Moritz Eberl**

October 2018 -- November 2019

<br>

***

<br>

### Presentations


<br>


#### Framing Effects in the Wild - Does News Framing Affect Public Opinion?

**Conference Presentation**

[Working Paper](https://github.com/nicolaiberk/bild/raw/EPSA22/paper/Manuscript_Framing.pdf) | 
[Slides](https://github.com/nicolaiberk/bild/raw/EPSA22/pres/Presentation.pdf)

June 2022, Conference of the European Political Science Association, Prague


<br>

#### Leading by Example? How Elite Behaviour affects Individual Vaccination Decisions

**Presentation of project idea**

June 2022, Political Behavior Workshop at Aarhus Universitet and EPSIP Colloquium HU Berlin


<br>


#### The Effect of News Framing on Issue Attitudes and Voting Behaviour

**Conference Presentation**

May 2022, Conference of the International Communication Association, Paris


<br>

#### Assessing Media Influence in Contemporary News Environments - Right-wing Media, Crime, and Anti-Immigration Attitudes

**Conference Presentation**

April 2022, European Graduate Network Conference, Florence


<br>

#### Migration, Crime and the Heterogeneous Impact of Emphasis Framing

**Presentation of working paper**

March 2022, Political Behavior and Institutions Section, Aarhus Universitet

<br>

#### Media Influence in Contemporary News Environments - Right-wing Media, Crime, and Anti-Immigration Attitudes
**Presentation of working paper** 

November 2021, Political Behavior Workshop Berlin-Brandenburg, WZB Berlin

<br>


#### The effect of changing news frames
**Project presentation**

[Slides](https://www.dropbox.com/s/hwoy5bmp2vxpt8x/PSAI_20211009.pdf?dl=0)

October 2021, PSAI Conference, University College Dublin.

<br>

#### Hypodermic Needle After All? Individual-level moderators of framing effects
**Presentation of working paper**

[Slides](https://raw.githubusercontent.com/nicolaiberk/bild/main/pres/Presentation_20210503.pdf)

June 2020, EPSIP Colloquium, HU Berlin, Germany



<br>


#### Measuring Rhetorical Similarity with Supervised Machine Learning
**Presentation of working paper**

[Slides](https://www.dropbox.com/s/5zo85ak86hkujl0/Draft141020%20%281%29.pdf?dl=0)

October 2020, EPSIP Colloquium, HU Berlin, Germany

<br>

#### To lead or to follow? Mainstream parties’ strategies and radical right success in Germany
**Presentation of an ongoing project at the [Hot Politics Lab](http://www.hotpolitics.eu/)**

[Slides](https://www.dropbox.com/s/xyupoug7rje3n16/To_lead_or_to_follow.pdf?dl=0) | 
[Github](github.com/nicolaiberk/ImEm)

October 2019, University of Amsterdam, Netherlands

<br>

#### Threat or Corrective? - The Causal Effect of Challenger Party Entrance on Political Trust
**Presentation of a working paper at the 2019 Summer School of the ECPR Standing Group on Political Parties**

[Slides](https://www.dropbox.com/s/krah2hbtidgc623/Challenger_Parties_and_Political_Trust__Presentation_for_ECPR_SG_Political_Parties_Summer_School%20%2811%29.pdf?dl=0) | 
[Working Paper](https://www.dropbox.com/s/6qp8nyr0dfriuwz/Berk_ThreatOrCorrective_WP.pdf?dl=0)

August 2019, University of Aarhus, Denmark

<br>

***

<br>

### Teaching

<br>

#### Supervised Machine Learning with Imbalanced Data
**Self-designed workshop introducing different techniques to deal with imbalanced data in supervised classification problems.**

[Github](https://github.com/nicolaiberk/Imbalanced) | 
[Slides](imbalance.html)

May 2022, CompText Conference, Dublin, Ireland


<br>

#### Intro to R and Statistics
**Taught two independent labs as addition to Prof. Mark Kayser's Stats I lecture for Master students, focusing on the R programming language**

September - December 2020 and 2021, Hertie School, Berlin, Germany

<br>

***

<br>

### Data

<br>

#### Word embeddings of German Newspaper articles
**Word embedding model of over 2.2M German newspaper articles 2013-2021 (Bild, Frankfurter Allgemeine, Spiegel Online, Süddeutsche Zeitung, TAZ, Welt).**

[Dataset](https://www.dropbox.com/s/xmljzunlx337dfz/word2vec.wordvectors?dl=1) | [Github](https://github.com/nicolaiberk/GermanNPEmbs)

August 2021, HU Berlin, Germany

<br>

#### EUSpeech v2.0. A dataset of 11,466 speeches by European Leaders
**In charge of data collection using web-scrapers**

[Dataset](https://osf.io/c79ha/) | 
[Report](https://osf.io/preprints/socarxiv/a4uyw/)

September 2018 -- July 2020, University of Amsterdam, Netherlands

<br>

#### AUTNES Online Panel Study 2017
**Responsible for data cleaning, manual coding and preparation of questionnaires.**

[Dataset](https://data.aussda.at/dataset.xhtml?persistentId=doi:10.11587/I7QIYJ)

April 2017 - March 2018, University of Vienna, Austria

<br>

#### AUTNES Comparative Study of Electoral Systems Post-Election Survey 2017
**Responsible for data cleaning, manual coding and preparation of questionnaires.**

[Dataset](https://data.aussda.at/dataset.xhtml?persistentId=doi:10.11587/GDBBPJ)

April 2017 - March 2018, University of Vienna, Austria

<br>

***

<br>

### Blog-posts

<br>

#### “Silberstein und Kern - hat der Skandal der SPÖ geschadet?”
**Blog-post (Coauthored with Markus Wagner) on a scandal in the Austrian Lower House Election 2017; also covered by Austrian daily newspaper “Der Standard”.**

[Blogpost](https://viecer.univie.ac.at/blog/detail/news/silberstein-und-kern-hat-der-skandal-der-spoe-geschadet/?cHash=d87f628d8c10b27c101d3ffb1dbe240f&tx_news_pi15Baction5D=detail&tx_news_pi15Bcontroller5D=News) | 
[News article](https://derstandard.at/2000076132168/Causa-Silberstein-schadete-SPOe-viel-weniger-als-vermutet)

March 2018

<br>

***

### Dormant


<br>

#### Using transfer learning to measure ideological bias
**Project (with Tom Arend) assessing the performance of deep neural networks transferred from one domain (party press releases) to another (news)**

[Blogpost](nlpdl_project.html) | 
[Report](https://raw.githubusercontent.com/nicolaiberk/nlpdl_project/main/reports/final-report-latex/final-report.pdf) | 
[Github](https://github.com/nicolaiberk/nlpdl_project)
  

March 2021 -- today



<br>



#### Apart - Affective Polarization in Text
**Collaborative project (with João Areal Neto and Phillip Mendoza) measuring hostility in parliaments using targeted sentiment analysis**

[Github](https://github.com/nicolaiberk/Apart)

September 2019 -- February 2020 



</div>

